### ISSUE TITLE
barra pesquisa

### ISSUE THREAD

**Issue by Wander27Rodrigues** [Lu1sHenrique/AppFinancas#22]
Ajustar barra de pesquisa para que seja auto complet

![image](https://user-images.githubusercontent.com/48796830/203100505-b5d5c2bd-7bdb-42b7-9d04-a51d5cba6ca5.png)

semelhante a realizada em 
![image](https://user-images.githubusercontent.com/48796830/203100590-ffd137c3-6040-42a6-b895-3f98cb32a41f.png)

**Comment by Lu1sHenrique** [comment]
Corrigido, foi feito semelhante a já utilizada.
