### ISSUE TITLE
active icon tabBaR

### ISSUE THREAD

**Issue by Wander27Rodrigues** [Lu1sHenrique/AppFinancas#23]
**Descreva o bug**
background icon não fica ativo
![image](https://user-images.githubusercontent.com/48796830/203101054-9c771e55-dcd4-48a8-9704-674881a20681.png)

**Comportamento esperado**
deve ficar ativo quando estiver na pagina, assim facilita a localização do usuário

**Comment by Lu1sHenrique** [comment]
Foi corrigido. Foi adicionado os parâmetros de focused e size na função tabBarIcon para receber os valores de foco e tamanho que vem do navigator, adicionei também uma View por volta do icone pra estilizar melhor.

Navigator: 

`<Bottom.Navigator
      screenOptions={{
        headerShown: false,
        tabBarHideOnKeyboard: true,
        tabBarStyle:{
          borderTopColor: 'transparent',
          right: 10,
          backgroundColor: "#fff",
          borderTopLeftRadius: 20,
          borderTopRightRadius: 20,
          height: 75,
          paddingTop: 10
        },
        tabBarActiveTintColor: colors.white,
        tabBarInactiveTintColor: colors.gray,
        tabBarShowLabel:false
      }}
      >`

Screen: 
`<Bottom.Screen 
        name="Home"
        component={Home}
        options={{
          tabBarIcon: () => (
              <Ionicons name="home" color="#dadada" size={30} />
            ),
            tabBarAccessibilityLabel:"Home",
        }}
        />`
